### ISSUE TITLE
Segfault when emitting large wasm files (but only for walrus in debug mode)

### ISSUE THREAD

**Issue by nhynes** [rustwasm/walrus#103]
### Describe the Bug

`walrus::Module::emit_wasm_file` segfaults when the Wasm module is ~1.5 MiB, but not when Walrus is compiled with `--release`. But, based on the stack trace, the issue seems to be infinitely [visiting `ExprId`](https://github.com/rustwasm/walrus/blob/master/src/ir/mod.rs#L1176), so maybe it's not a size issue?

### Steps to Reproduce

Example program:

```rust
fn main() -> Result<(), failure::Error> {
    let wasm_path = std::env::args_os().nth(1).unwrap();
    walrus::Module::from_file(&wasm_path)?.emit_wasm_file(&wasm_path)?;
    Ok(())
}
```

1. Compile a big Wasm file (e.g. [RustPython](https://github.com/RustPython/RustPython))
2. `cargo run -- /path/to/big.wasm`
3. Observe segfault
4. `cargo run --release -- /path/to/big.wasm`
5. Observe no segfault

### Actual Behavior

[stack trace](https://gist.github.com/nhynes/02ff67fdeaad008de8026706fc296c86)

### Additional Context

* rustc 1.38.0-nightly (4b65a86eb 2019-07-15) x86_64-unknown-linux-gnu
* walrus >= 0.7

**Comment by alexcrichton** [comment]
Thanks for the report! This looks to be a stack overflow which can happen in debug mode on huge functions due to the compiled version of walrus taking egregious amounts of stack space. You can fix this with release mode (as you've found) or by tweaking your OS to increase the size of the stack of the main thread.
